name: Pull requests

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - 'current'
          - 'lts/*'

    name: Lint, Build, and Test on Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies
        with:
          version: ${{ matrix.node }}

      - name: Setup Solana Test Validator
        id: start-test-validator
        uses: ./.github/workflows/actions/setup-validator

      - name: Lint, Build, and Test
        uses: ./.github/workflows/actions/lint-build-and-test

      - name: Build Docs
        description: >
          We run this step in the context of PRs to make sure that the change does not prevent the 
          docs from being built
        run: pnpm compile:docs

      - name: Stop Test Validator
        if: always() && steps.start-test-validator.outcome == 'success'
        run: kill ${{ steps.start-test-validator.outputs.pid }}
